version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backend:/sqlite
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/backend/app
      - DATABASE_URL=sqlite:///./sqlite/hiboutik.db
      - DB_CLIENT:'sqlite3'
      - DB_FILENAME:'/backend/sqlite/hiboutik.db'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/src
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./backend/sqlite

# version: '3.8'

# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     volumes:
#       - ./backend:/app
#     ports:
#       - "8000:8000"
#     environment:
#       - PYTHONPATH=/app
#       - DATABASE_URL=sqlite:///./sqlite/hiboutik.db
#     depends_on:
#       - db

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     volumes:
#       - ./frontend:/src
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend

#   db:
#     image: nouchka/sqlite3:latest
#     volumes:
#       - ./sqlite_data:./backend/sqlite
#     restart: always